name: zego_uikit
description: ZegoUIKit is a low-code offering with pre-built and UI-ready components, such as AudioVideoView, CameraButtons, etc. Save time and assemble features fast with ZegoUIKit.
version: 2.28.3
homepage: https://www.zegocloud.com/

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_plugin_adapter: ^2.13.5

  zego_express_engine: ^3.18.0
  zego_zpns: ^2.6.0+3
  zego_callkit: ^1.0.0+4

  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  flutter_logs: ^2.2.1
  native_device_orientation: ^2.0.3
  wakelock_plus: ^1.2.10
  cached_network_image: ^3.3.0
  file_picker: ^8.0.6
  path: ^1.8.3
  plugin_platform_interface: ^2.1.8
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0 # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any
  lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
  plugin:
    platforms:
      android:
        package: com.zegocloud.uikit.zego_uikit_plugin
        pluginClass: ZegoUikitPlugin
      ios:
        pluginClass: ZegoUikitPlugin
